name: linguamate
description: A personal AI language learning app.
publish_to: "none"
version: 1.47.2+73

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  flutter_tts: ^4.2.5
  speech_to_text: ^7.5.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - web/icons/Shili-192-v052.png
    - assets/images/shili_coach_card_v14.jpg
    - assets/images/shili_avatar_v14.jpg
